services:
  readit_api:
    build: .
    image: readit_api
    command: uvicorn app.main:app --host 0.0.0.0 --port 8080 --reload
    volumes:
      - ./app:/app
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - redis
      - db
    dns:
      - 8.8.8.8
      - 8.8.4.4

  celery:
    build: .
    image: readit_api
    command: celery -A app.dependency.celery_service.celery_app worker --loglevel=info
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
    env_file:
      - .env
    depends_on:
      - redis
      - db
    dns:
      - 8.8.8.8
      - 8.8.4.4

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  db:
    image: mysql:8
    env_file:
      - .env
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    command:
      - --character-set-server=utf8

volumes:
  db_data:
